In [2]:
import numpy as np

In [4]:
from thinning import sample_hawkes_process_thinning_true_vectorised
from utils import exp_kernel_vectorised, constant_background, plot_counting_process
from mle import log_likelihood

In [25]:
mu, alpha, delta = 1, 1, 2

In [26]:
hawkes_seed=244659525681607163626346801839259531332

max_T = 5.
hawkes_realisation = sample_hawkes_process_thinning_true_vectorised(max_T, constant_background, exp_kernel_vectorised, seed=hawkes_seed)
N = len(hawkes_realisation)

In [27]:
hawkes_realisation

[0.10153662201681525,
 1.0186454364123092,
 3.1778917433953993,
 4.4237004367232675]

In [47]:
hawkes_realisation = np.array(hawkes_realisation)[np.newaxis, :]

In [48]:
differences_from_max_T = max_T - hawkes_realisation

In [49]:
differences_from_max_T

array([[4.89846338, 3.98135456, 1.82210826, 0.57629956]])

In [50]:
np.sum(np.exp(-delta*differences_from_max_T) - 1)

-3.657639426640536

In [51]:
np.sum(np.exp(-differences_from_max_T)**delta - 1)

-3.657639426640536

In [52]:
np.sum(np.exp(-differences_from_max_T)**delta) - N

-3.6576394266405363

In [59]:
differences_mat = np.tril(hawkes_realisation.T - hawkes_realisation)

In [66]:
differences_mat

array([[0.        , 0.        , 0.        , 0.        ],
       [0.91710881, 0.        , 0.        , 0.        ],
       [3.07635512, 2.15924631, 0.        , 0.        ],
       [4.32216381, 3.405055  , 1.24580869, 0.        ]])

In [76]:
np.tril(np.exp(-delta*differences_mat), k=-1)

array([[0.        , 0.        , 0.        , 0.        ],
       [0.15973843, 0.        , 0.        , 0.        ],
       [0.00212771, 0.01331995, 0.        , 0.        ],
       [0.00017612, 0.00110257, 0.08277598, 0.        ]])

In [69]:
np.sum(np.tril(np.exp(-delta*(hawkes_realisation.T - hawkes_realisation)), k=-1), axis=1)

array([0.        , 0.15973843, 0.01544765, 0.08405467])

In [85]:
def lower_triangular_to_array_of_arrays(matrix):
    result = []
    n = matrix.shape[0]
    for i in range(1, n):
        row = matrix[i, :i]  # Extract nonzero elements in the current row
        if len(row) > 0:
            result.append(row)
    return result

In [86]:
lower_triangular_to_array_of_arrays(differences_mat)

[array([0.91710881]),
 array([3.07635512, 2.15924631]),
 array([4.32216381, 3.405055  , 1.24580869])]